name: Jovan Savic
title: Jekyll Gulp Starter Kit
markdown: redcarpet
baseurl: beproductive-site
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
include: ["_pages"]
